apiVersion: v1
data:
  secretkey: dzFGTkNCQk0yaGZ4dXBwcE42SS9QT0xuNjNIdG1VcjZDNzF3RTNDdXlpL1FtZDBhZ1R3ZkF6MFU0dW1KSWZIRgpCVGVXeVpsaUNycWZYMWdoYVcwZUhsY3grU1NHQTRDWS9PalNYTmE3S0wrUEc3VDBEdk5ZU0tveWZUOVhjMWpTCkdNMFh6ajlYU2xyb093dnhBR3R3Vk5JMGhMOGgySXJ3MTc1a3Z3MEJpR0U9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
